from __future__ import annotations

import csv
import html
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "assets" / "data"
PROJECT_ROOT = ROOT.parents[1]
ANALYSIS_DATA_DIR = PROJECT_ROOT / "work" / "work" / "data"
ANALYSIS_RESULTS_DIR = PROJECT_ROOT / "work" / "work" / "results"


def read_csv(name: str) -> list[dict[str, str]]:
    with (DATA_DIR / name).open("r", encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def read_csv_path(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def to_int(value: str) -> int:
    return int(str(value).replace(",", "").strip())


def compact_dataset_name(name: str) -> str:
    text = "·".join(part.strip() for part in name.split("·"))
    text = text.replace("지선 ", "지선")
    return text


def rate_per_million(count: int, denominator: int) -> float:
    if denominator <= 0:
        return 0.0
    return round(count / denominator * 1_000_000, 3)


def format_int(value: int) -> str:
    return f"{value:,}"


def format_rate(value: float) -> str:
    return f"{value:g}"


def format_percent(value: float | None) -> str:
    if value is None:
        return "-"
    return f"{value * 100:.2f}%"


def display_region(value: str) -> str:
    return str(value).replace("광주전남", "광주·전남")


def metric_cell(row: dict, key: str) -> str:
    count = row[key]
    return (
        "              <td>"
        f"<span class=\"cell-main\">{format_int(count)}</span>"
        "</td>"
    )


def render_history_rows(history: list[dict], focus_dataset: str) -> str:
    rows = []
    for row in history:
        dataset = html.escape(row["dataset"])
        focus = "true" if row["dataset"] == focus_dataset else "false"
        rows.append(
            "\n".join(
                [
                    f"            <tr data-focus=\"{focus}\">",
                    f"              <td>{dataset}</td>",
                    f"              <td>{format_int(row['rows'])}</td>",
                    metric_cell(row, "stem"),
                    metric_cell(row, "sameSigungu"),
                    metric_cell(row, "gwangjuJeonnam"),
                    metric_cell(row, "national"),
                    "            </tr>",
                ]
            )
        )
    return "\n".join(rows)


def update_index_history_table(history: list[dict], focus_dataset: str) -> None:
    index_path = ROOT / "index.html"
    html_text = index_path.read_text(encoding="utf-8")
    replacement = (
        '<tbody id="history-body">\n'
        "            <!-- Generated by tools/build_site_data.py; JS enhances filtering. -->\n"
        f"{render_history_rows(history, focus_dataset)}\n"
        "            </tbody>"
    )
    updated, replacements = re.subn(
        r'<tbody\s+id=["\']history-body["\'][^>]*>.*?</tbody>',
        replacement,
        html_text,
        count=1,
        flags=re.S,
    )
    if replacements != 1:
        raise RuntimeError("Could not find history table body in index.html")
    index_path.write_text(updated, encoding="utf-8")


def load_regional_thresholds() -> dict:
    candidates = list(
        ANALYSIS_RESULTS_DIR.glob("regional_thresholds_2026_시·도지사_advance_w0.7_*.json")
    )
    if not candidates:
        return {"runs": [], "regions": []}

    def load_payload(path: Path) -> dict:
        return json.loads(path.read_text(encoding="utf-8"))

    loaded = [(path, load_payload(path)) for path in candidates]
    loaded.sort(
        key=lambda item: max(
            (run.get("config", {}).get("iters", 0) for run in item[1].get("analyses", [])),
            default=0,
        ),
        reverse=True,
    )
    source_path, payload = loaded[0]
    analyses = payload.get("analyses", [])
    by_weight = {str(run["config"]["weight"]): run for run in analyses}
    default = by_weight.get("0.7") or (analyses[0] if analyses else {"regions": [], "config": {}})
    thresholds = [str(value) for value in default.get("config", {}).get("thresholds", range(1, 11))]

    regions = []
    for item in default.get("regions", []):
        threshold_probabilities = {
            threshold: {
                "value": item.get("threshold_probabilities", {}).get(threshold),
                "text": format_percent(item.get("threshold_probabilities", {}).get(threshold)),
            }
            for threshold in thresholds
        }
        regions.append(
            {
                "region": item["region"],
                "observed": item["observed_equal_pairs"],
                "possiblePairs": item["possible_pairs"],
                "pollingPlaces": item["polling_places"],
                "modelMean": round(item["mean_equal_pairs"], 3),
                "thresholdProbabilities": threshold_probabilities,
            }
        )
    regions.sort(
        key=lambda item: (
            -(item["thresholdProbabilities"].get("1", {}).get("value") or 0),
            item["region"],
        )
    )
    return {
        "source": source_path.name,
        "thresholds": [int(value) for value in thresholds],
        "runs": [
            {
                "model": run["config"]["model"],
                "weight": run["config"]["weight"],
                "iterations": run["config"]["iters"],
            }
            for run in analyses
        ],
        "regions": regions,
    }


def load_regional_observed_details(focus_dataset: str) -> dict:
    detail_path = ANALYSIS_DATA_DIR / "equal_pairs_detail.csv"
    if not detail_path.exists():
        return {"regions": [], "pairs": []}

    rows = [
        row for row in read_csv_path(detail_path)
        if compact_dataset_name(row["dataset"]) == focus_dataset
    ]
    counts: dict[str, int] = {}
    pairs = []
    for row in rows:
        region = display_region(row["권역"])
        counts[region] = counts.get(region, 0) + 1
        pairs.append(
            {
                "region": region,
                "tightness": row["tightness"],
                "candidate1": to_int(row["민주"]),
                "candidate2": to_int(row["국힘"]),
                "place1": row["지역1"],
                "place2": row["지역2"],
            }
        )

    regions = [
        {"region": region, "observed": count}
        for region, count in sorted(counts.items(), key=lambda item: (-item[1], item[0]))
    ]
    return {"regions": regions, "pairs": pairs}


def main() -> None:
    equal_rows = read_csv("equal_pair_counts.csv")
    pair_rows = read_csv("pair_counts.csv")

    pair_lookup = {
        compact_dataset_name(row["dataset"]): {
            "rows": to_int(row["rows"]),
            "stemPairs": to_int(row["stem(구시군+읍면동stem)"]),
            "sameSigunguPairs": to_int(row["같은 구시군"]),
            "sameSidoPairs": to_int(row["같은 광역권(시도)"]),
            "gwangjuJeonnamPairs": to_int(row["광주+전남 통합"]),
            "nationalPairs": to_int(row["전국 전체"]),
        }
        for row in pair_rows
    }

    history = []
    for row in equal_rows:
        dataset = compact_dataset_name(row["dataset"])
        pairs = pair_lookup[dataset]
        counts = {
            "stem": to_int(row["stem"]),
            "sameSigungu": to_int(row["같은 구시군"]),
            "sameSido": to_int(row["광역권(시도)"]),
            "gwangjuJeonnam": to_int(row["광주+전남 통합"]),
            "national": to_int(row["전국 전체"]),
            "nationalLoose": to_int(row["전국_loose(한정당0포함)"]),
        }
        denominators = {
            "stem": pairs["stemPairs"],
            "sameSigungu": pairs["sameSigunguPairs"],
            "sameSido": pairs["sameSidoPairs"],
            "gwangjuJeonnam": pairs["gwangjuJeonnamPairs"],
            "national": pairs["nationalPairs"],
        }
        history.append(
            {
                "dataset": dataset,
                "rows": pairs["rows"],
                **counts,
                "denominators": denominators,
                "ratesPerMillion": {
                    key: rate_per_million(counts[key], denominator)
                    for key, denominator in denominators.items()
                },
            }
        )

    focus_dataset = "지선9회(2026)·사전투표"
    focus_counts = next(row for row in history if row["dataset"] == focus_dataset)
    focus_pairs = pair_lookup[focus_dataset]

    scope_items = [
        {
            "label": "분할동",
            "value": f"{focus_counts['stem']:,}",
            "count": focus_counts["stem"],
            "denominator": focus_pairs["stemPairs"],
            "text": "송도1동·송도2동 같은 분할동 기준. 가장 좁은 비교범위다.",
        },
        {
            "label": "같은 구시군",
            "value": f"{focus_counts['sameSigungu']:,}",
            "count": focus_counts["sameSigungu"],
            "denominator": focus_pairs["sameSigunguPairs"],
            "text": "행정권역을 공유하는 읍면동 쌍(pair) 전체를 비교한다.",
        },
        {
            "label": "광역권",
            "value": f"{focus_counts['gwangjuJeonnam']:,}",
            "count": focus_counts["gwangjuJeonnam"],
            "denominator": focus_pairs["gwangjuJeonnamPairs"],
            "text": "기본 광역권은 분석 목적상 광주와 전남을 하나의 권역으로 묶은 기준이다.",
        },
        {
            "label": "전국 전체",
            "value": f"{focus_counts['national']:,}",
            "count": focus_counts["national"],
            "denominator": focus_pairs["nationalPairs"],
            "text": "전국의 가능한 모든 쌍(pair). 사후탐색 효과가 가장 크다.",
        },
    ]

    payload = {
        "generatedAt": "2026-06-10",
        "focusDataset": focus_dataset,
        "scopeItems": scope_items,
        "history": history,
        "pairCounts": pair_lookup,
        "regionalObserved": load_regional_observed_details(focus_dataset),
        "regionalThresholds": load_regional_thresholds(),
        "nearMatch": {
            "model": "모델 2(Model 2) w=0.7",
            "iterations": 500,
            "items": [
                {"delta": "±0", "observed": 8, "mean": 2.6, "ci": "[0, 6]"},
                {"delta": "±1", "observed": 28, "mean": 24.8, "ci": "[15, 35]"},
                {"delta": "±2", "observed": 66, "mean": 68.6, "ci": "[53, 86]"},
                {"delta": "±3", "observed": 123, "mean": 133.6, "ci": "[113, 157]"},
            ],
        },
    }

    output = DATA_DIR / "site-data.js"
    output.write_text(
        "window.SITE_DATA = "
        + json.dumps(payload, ensure_ascii=False, indent=2)
        + ";\n",
        encoding="utf-8",
    )
    print(f"wrote {output}")
    update_index_history_table(history, focus_dataset)
    print(f"updated {ROOT / 'index.html'}")


if __name__ == "__main__":
    main()
