from __future__ import annotations

import hashlib
import json
import re
import sys
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from threading import Thread
from urllib.parse import urlsplit
from urllib.request import urlopen


ROOT = Path(__file__).resolve().parents[1]
REQUIRED_HTTP_PATHS = [
    "/",
    "/docs.html",
    "/docs.js",
    "/styles.css",
    "/app.js",
    "/robots.txt",
    "/site.webmanifest",
    "/assets/chart1_scope.png",
    "/assets/chart2_calibration.png",
    "/assets/data/site-data.js",
    "/assets/data/equal_pair_counts.csv",
    "/assets/data/pair_counts.csv",
    "/assets/data/DATA_DICTIONARY.md",
    "/assets/data/integrity-manifest.json",
    "/QA_REPORT.md",
    "/README_DEPLOY.md",
    "/VERCEL_DASHBOARD_DEPLOY.md",
    "/PUBLICATION_STATUS.md",
    "/DEPLOYMENT_REQUEST.md",
]


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def check_local_refs() -> None:
    html = read_text(ROOT / "index.html") + "\n" + read_text(ROOT / "docs.html")
    refs = re.findall(r'(?:src|href)="(\./[^"#]+)"', html)
    missing = []
    for ref in refs:
        target = ROOT / urlsplit(ref).path.removeprefix("./")
        if not target.exists():
            missing.append(ref)
    if missing:
        raise AssertionError("Missing local references: " + ", ".join(missing))


def check_no_local_paths() -> None:
    files = [
        ROOT / "index.html",
        ROOT / "docs.html",
        ROOT / "styles.css",
        ROOT / "app.js",
        ROOT / "docs.js",
        ROOT / "assets" / "data" / "site-data.js",
        ROOT / "README_DEPLOY.md",
        ROOT / "VERCEL_DASHBOARD_DEPLOY.md",
        ROOT / "PUBLICATION_STATUS.md",
        ROOT / "DEPLOYMENT_REQUEST.md",
    ]
    bad_patterns = ["C:\\Users", "../work", "TODO", "FIXME", "undefined"]
    hits = []
    for path in files:
        text = read_text(path)
        for pattern in bad_patterns:
            if pattern in text:
                hits.append(f"{path.name}: {pattern}")
    if hits:
        raise AssertionError("Unexpected deploy text found: " + ", ".join(hits))


def check_site_data() -> None:
    text = read_text(ROOT / "assets" / "data" / "site-data.js")
    html = read_text(ROOT / "index.html")
    docs_html = read_text(ROOT / "docs.html")
    docs_js = read_text(ROOT / "docs.js")
    guide_md = read_text(ROOT / "assets" / "data" / "README.md")
    required = [
        '"focusDataset": "지선9회(2026)·사전투표"',
        '"stem": 1',
        '"sameSigungu": 1',
        '"sameSido": 7',
        '"gwangjuJeonnam": 8',
        '"national": 10',
        '"nationalPairs": 6327903',
        '"ratesPerMillion"',
        '"regionalObserved"',
        '"regionalThresholds"',
        '"thresholdProbabilities"',
        '"jointProbabilities"',
        '"pAText": "0.587%"',
        '"pBText": "0.825%"',
        '"pABText": "0.0110%"',
        '"iterations": 50000',
        '"region": "대구"',
        '"region": "경상북"',
        '"nearMatch"',
        '"label": "분할동"',
        '"label": "광역권"',
        '"value": "1"',
        '"value": "8"',
        '"value": "10"',
    ]
    missing = [item for item in required if item not in text]
    if missing:
        raise AssertionError("site-data.js missing expected values: " + ", ".join(missing))

    html_required = [
        'data-focus="true"',
        "지선9회(2026)·사전투표",
        "쌍둥이 득표수 일치, 정말 가능한 확률일까?",
        "광주·전남 5쌍",
        "모델 검증: 근접 일치는 맞는데, 정확 일치는 높다",
        '<th>광역권</th>',
        '<th>10개 이상</th>',
        '<span class="cell-main">10</span>',
        "모델 2(Model 2): 지역적응형 사후예측 w=0.7",
        "모델 2(Model 2): 지역적응형 사후예측",
        "사후예측(posterior predictive)",
        "한 줄 요약: 실제 선거 데이터의 지역별 쏠림 특성을 시뮬레이션 프로그램에 넣고 같은 조건의 가상 선거를 20만 번 다시 치러 본 것이다.",
        "같은 조건의 가상 선거를 20만 번 다시 치렀다",
        "이 말은 이미 관측된 지역 구조를 받아들였을 때 비슷한 일이 얼마나 다시 생기는지 보는 검증이라는 뜻이다.",
        "50,000회 반복",
        "각 사건은 얼마나 자주 나오고, 둘은 얼마나 자주 함께 나오나",
        '<tbody id="joint-probability-body"></tbody>',
        "P(B|A)",
        "지역 인구 구조 변동",
        "이 분석은 희귀성과 재현성을 평가할 뿐",
        "공개 재현 패키지",
        "https://github.com/MinS-J/equal-vote",
        "https://github.com/MinS-J/equal-vote/releases/tag/v2026-06-10",
        "equal-vote-inputs.zip",
        "/_vercel/insights/script.js",
        "window.va",
        "Generated by tools/build_site_data.py",
    ]
    html_missing = [item for item in html_required if item not in html]
    if html_missing:
        raise AssertionError("index.html missing static history fallback: " + ", ".join(html_missing))

    expected_section_order = [
        '<section id="history"',
        '<section id="method"',
        '<section id="simulation"',
        '<section id="validation"',
        '<section id="regional"',
    ]
    positions = [html.find(marker) for marker in expected_section_order]
    if any(position < 0 for position in positions) or positions != sorted(positions):
        raise AssertionError("Expected section order is history -> method -> simulation -> validation -> regional")

    expected_nav_order = [
        '<a href="#history">전국데이터</a>',
        '<a href="#method">기준</a>',
        '<a href="#simulation">시뮬레이션</a>',
        '<a href="#validation">모델검증</a>',
        '<a href="#regional">지역분석</a>',
    ]
    nav_positions = [html.find(marker) for marker in expected_nav_order]
    if any(position < 0 for position in nav_positions) or nav_positions != sorted(nav_positions):
        raise AssertionError("Expected nav order is 전국데이터 -> 기준 -> 시뮬레이션 -> 모델검증 -> 지역분석")

    docs_required = [
        "재현성 문서",
        'id="doc-body"',
        "docs.js",
        "재현 가이드",
        "데이터 사전",
        "분석 요약 원문",
        "사이트 QA 기록",
        "/_vercel/insights/script.js",
        "window.va",
    ]
    docs_missing = [item for item in docs_required if item not in docs_html]
    if docs_missing:
        raise AssertionError("docs.html missing expected markers: " + ", ".join(docs_missing))

    docs_js_required = [
        "DOCS",
        "./assets/data/README.md",
        "./assets/data/DATA_DICTIONARY.md",
        "./assets/data/equal_vote_probability_summary.md",
        "./QA_REPORT.md",
        "renderMarkdown",
    ]
    docs_js_missing = [item for item in docs_js_required if item not in docs_js]
    if docs_js_missing:
        raise AssertionError("docs.js missing expected markers: " + ", ".join(docs_js_missing))

    guide_required = [
        "Public Reproducibility Package",
        "https://github.com/MinS-J/equal-vote",
        "equal-vote-precomputed.zip",
    ]
    guide_missing = [item for item in guide_required if item not in guide_md]
    if guide_missing:
        raise AssertionError("assets/data/README.md missing release markers: " + ", ".join(guide_missing))

    forbidden = [
        "M2b",
        "proxy",
        "대리 기준",
        "줄기명(stem)",
        "<th>광주+전남</th>",
        "chart-gallery",
        "chart3_pairwise.png",
        "chart4_songdo.png",
        "chart5_scope3model.png",
        "chart6_nearmatch4.png",
        'id="hero-metrics"',
        "두 곳에서 두 후보의 표가 동시에 같았다",
        "10 / 6,327,903",
        "1.58 / 백만 pair",
    ]
    found = [item for item in forbidden if item in html]
    if found:
        raise AssertionError("index.html still contains old presentation markers: " + ", ".join(found))


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def check_integrity_manifest() -> None:
    manifest_path = ROOT / "assets" / "data" / "integrity-manifest.json"
    manifest = json.loads(read_text(manifest_path))
    if manifest.get("algorithm") != "sha256":
        raise AssertionError("integrity manifest algorithm must be sha256")

    failures = []
    for entry in manifest.get("files", []):
        path = ROOT / entry["path"]
        if not path.exists():
            failures.append(f"missing {entry['path']}")
            continue
        size = path.stat().st_size
        digest = sha256(path)
        if size != entry["bytes"] or digest != entry["sha256"]:
            failures.append(f"mismatch {entry['path']}")

    if failures:
        raise AssertionError("integrity manifest failures: " + ", ".join(failures))


def check_http_serving() -> None:
    class QuietHandler(SimpleHTTPRequestHandler):
        def log_message(self, format: str, *args) -> None:
            return

    server = ThreadingHTTPServer(("127.0.0.1", 0), QuietHandler)
    port = server.server_address[1]
    thread = Thread(target=server.serve_forever, daemon=True)

    cwd = Path.cwd()
    try:
        import os

        os.chdir(ROOT)
        thread.start()
        for path in REQUIRED_HTTP_PATHS:
            with urlopen(f"http://127.0.0.1:{port}{path}", timeout=5) as response:
                body = response.read(64)
                if response.status != 200 or not body:
                    raise AssertionError(
                        f"{path} failed: status={response.status}, bytes={len(body)}"
                    )
    finally:
        server.shutdown()
        server.server_close()
        import os

        os.chdir(cwd)


def main() -> int:
    checks = [
        check_local_refs,
        check_no_local_paths,
        check_site_data,
        check_integrity_manifest,
        check_http_serving,
    ]
    for check in checks:
        check()
        print(f"ok {check.__name__}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
